procédure Socket_AfficherErreurConnexion()
Info("La connexion au serveur de synchronisation a été perdue." + RC + ...
"Impossible de se reconnecter." + RC + ...
"La synchronisation multi-utilisateurs est désactivée." + RC + RC + ...
"Veuillez redémarrer l'application.")
Procédure globale Socket_AfficherPromotionServeur

