procédure Tranfertvol2()
si TABLE_vol1_Seletion_Affaires>0 alors
sLigne est une chaîne
pour toute ligne i de TABLE_vol1_Seletion_Affaires
si TABLE_vol1_Seletion_Affaires.COL_Select[i]=Vrai alors
ONG_Recherche_et_selection
= 2
sLigne
= TAB+TAB+TABLE_vol1_Seletion_Affaires.COL_DELAI[i]+...
TAB+TABLE_vol1_Seletion_Affaires.COL_COCLI[i]+...
TAB+TABLE_vol1_Seletion_Affaires.COL_NAF[i]+...
TAB+TABLE_vol1_Seletion_Affaires.COL_COCDE[i]+...
TAB+TABLE_vol1_Seletion_Affaires.COL_DESA[i]+...
TAB+TABLE_vol1_Seletion_Affaires.COL_PIECE[i]+...
TAB+TABLE_vol1_Seletion_Affaires.COL_DOSSIER[i]+...
TAB+TAB+
TAB+TABLE_vol1_Seletion_Affaires.COL_QTEAFREST[i]
fin
fin
sinon Erreur("Rien à afficher, veuillez lancer la recherche")
Procédure locale VerrouillerLignePourSaisie

